---
apiVersion: v1
stringData:
  project: default
  type: git
  url: ${{values.destination.repo}}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: guestbook
  namespace: argocd
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: ${{values.destination.repo}}
        targetRevision: HEAD
        path: helm
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}
