---
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.destination.repo}}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "git@${{values.destination.host}}:${{values.destination.owner}}/${{values.destination.repo}}.git"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: "git@${{values.destination.host}}:${{values.destination.owner}}/${{values.destination.repo}}.git"
        targetRevision: HEAD
        path: helm
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}
